CREATE TABLE IF NOT EXISTS conversations (
    id VARCHAR(36) PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    mode VARCHAR(16) DEFAULT 'CHAT' NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

ALTER TABLE conversations
    ADD COLUMN IF NOT EXISTS mode VARCHAR(16) DEFAULT 'CHAT' NOT NULL;

CREATE TABLE IF NOT EXISTS conversation_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(36) NOT NULL,
    role VARCHAR(16) NOT NULL,
    content CLOB NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_conversation_message
        FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS conversation_summaries (
    conversation_id VARCHAR(36) PRIMARY KEY,
    summary CLOB NOT NULL,
    last_message_id BIGINT NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_conversation_summary
        FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS agent_runs (
    run_id VARCHAR(36) PRIMARY KEY,
    request_id VARCHAR(100) NOT NULL,
    conversation_id VARCHAR(36) NOT NULL,
    conversation_mode VARCHAR(16) DEFAULT 'CHAT' NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP,
    finished_at TIMESTAMP NOT NULL,
    tool_steps_json CLOB,
    result_json CLOB,
    error_message CLOB,
    CONSTRAINT fk_agent_run_conversation
        FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE
);

ALTER TABLE agent_runs
    ADD COLUMN IF NOT EXISTS tool_steps_json CLOB;

ALTER TABLE agent_runs
    ADD COLUMN IF NOT EXISTS conversation_mode VARCHAR(16) DEFAULT 'CHAT' NOT NULL;

CREATE INDEX IF NOT EXISTS idx_conversations_updated_at
    ON conversations(updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_messages_conversation_id
    ON conversation_messages(conversation_id, id DESC);

CREATE INDEX IF NOT EXISTS idx_agent_runs_conversation_finished
    ON agent_runs(conversation_id, finished_at DESC);
