CREATE TABLE IF NOT EXISTS workspaces (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    type VARCHAR(16) DEFAULT 'MANAGED' NOT NULL,
    root_path VARCHAR(1024) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_workspace_root_path UNIQUE (root_path)
);

ALTER TABLE workspaces
    ADD COLUMN IF NOT EXISTS type VARCHAR(16) DEFAULT 'MANAGED' NOT NULL;

CREATE TABLE IF NOT EXISTS conversations (
    id VARCHAR(36) PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    workspace_id VARCHAR(36),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

ALTER TABLE conversations
    ADD COLUMN IF NOT EXISTS workspace_id VARCHAR(36);

ALTER TABLE conversations
    ADD CONSTRAINT IF NOT EXISTS fk_conversation_workspace
        FOREIGN KEY (workspace_id) REFERENCES workspaces(id);

CREATE TABLE IF NOT EXISTS conversation_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(36) NOT NULL,
    role VARCHAR(16) NOT NULL,
    content CLOB NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_conversation_message
        FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_conversations_updated_at
    ON conversations(updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_conversations_workspace_updated_at
    ON conversations(workspace_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_messages_conversation_id
    ON conversation_messages(conversation_id, id DESC);
